builtIn:
  urlPrefix: 'https://cdn.jsdelivr.net/gh/PrismJS/prism@1.30.0'
  themes:
    coy: '/themes/prism-coy.min.css'
    dark: '/themes/prism-dark.min.css'
    funky: '/themes/prism-funky.min.css'
    okaidia: '/themes/prism-okaidia.min.css'
    solarizedlight: '/themes/prism-solarizedlight.min.css'
    tomorrow: '/themes/prism-tomorrow.min.css'
    twilight: '/themes/prism-twilight.min.css'
    prism: '/themes/prism.min.css'
  plugins:
    - script: '/plugins/autoloader/prism-autoloader.min.js'
    - script: '/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js'
      dependencies:
        - script: '/plugins/toolbar/prism-toolbar.min.js'
          link: '/plugins/toolbar/prism-toolbar.min.css'

external:
  urlPrefix: 'https://cdn.jsdelivr.net/gh/PrismJS/prism-themes@1.9.0/themes'
  themes:
    a11y-dark: '/prism-a11y-dark.css'
    atom-dark: '/prism-atom-dark.css'
    base16-ateliersulphurpool.light: '/prism-base16-ateliersulphurpool.light.css'
    cb: '/prism-cb.css'
    coldark-cold: '/prism-coldark-cold.css'
    coldark-dark: '/prism-coldark-dark.css'
    coy-without-shadows: '/prism-coy-without-shadows.css'
    darcula: '/prism-darcula.css'
    dracula: '/prism-dracula.css'
    duotone-dark: '/prism-duotone-dark.css'
    duotone-earth: '/prism-duotone-earth.css'
    duotone-forest: '/prism-duotone-forest.css'
    duotone-light: '/prism-duotone-light.css'
    duotone-sea: '/prism-duotone-sea.css'
    duotone-space: '/prism-duotone-space.css'
    ghcolors: '/prism-ghcolors.css'
    gruvbox-dark: '/prism-gruvbox-dark.css'
    gruvbox-light: '/prism-gruvbox-light.css'
    holi-theme: '/prism-holi-theme.css'
    hopscotch: '/prism-hopscotch.css'
    laserwave: '/prism-laserwave.css'
    lucario: '/prism-lucario.css'
    material-dark: '/prism-material-dark.css'
    material-light: '/prism-material-light.css'
    material-oceanic: '/prism-material-oceanic.css'
    night-owl: '/prism-night-owl.css'
    nord: '/prism-nord.css'
    one-dark: '/prism-one-dark.css'
    one-light: '/prism-one-light.css'
    pojoaque: '/prism-pojoaque.css'
    shades-of-purple: '/prism-shades-of-purple.css'
    solarized-dark-atom: '/prism-solarized-dark-atom.css'
    synthwave84: '/prism-synthwave84.css'
    vs: '/prism-vs.css'
    vsc-dark-plus: '/prism-vsc-dark-plus.css'
    xonokai: '/prism-xonokai.css'
    z-touch: '/prism-z-touch.css'