builtIn:
  urlPrefix: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0'
  themes:
    default: '/styles/default.min.css'
    github: '/styles/github.min.css'
    github-dark: '/styles/github-dark.min.css'
    monokai: '/styles/monokai.min.css'
    monokai-sublime: '/styles/monokai-sublime.min.css'
    vs: '/styles/vs.min.css'
    vs2015: '/styles/vs2015.min.css'
    agate: '/styles/agate.min.css'
    androidstudio: '/styles/androidstudio.min.css'
    dracula: '/styles/dracula.min.css'
    nord: '/styles/nord.min.css'
    atom-one-dark: '/styles/atom-one-dark.min.css'
    atom-one-light: '/styles/atom-one-light.min.css'
    night-owl: '/styles/night-owl.min.css'
    shades-of-purple: '/styles/shades-of-purple.min.css'
    tokyo-night-dark: '/styles/tokyo-night-dark.min.css'
    tokyo-night-light: '/styles/tokyo-night-light.min.css'
