builtIn:
  urlPrefix: 'https://unpkg.com/@highlightjs/cdn-assets@11.11.1'
  themes:
    1c-light: '/styles/1c-light.min.css'
    a11y-dark: '/styles/a11y-dark.min.css'
    a11y-light: '/styles/a11y-light.min.css'
    agate: '/styles/agate.min.css'
    an-old-hope: '/styles/an-old-hope.min.css'
    androidstudio: '/styles/androidstudio.min.css'
    arduino-light: '/styles/arduino-light.min.css'
    arta: '/styles/arta.min.css'
    ascetic: '/styles/ascetic.min.css'
    atom-one-dark-reasonable: '/styles/atom-one-dark-reasonable.min.css'
    atom-one-dark: '/styles/atom-one-dark.min.css'
    atom-one-light: '/styles/atom-one-light.min.css'
    brown-paper: '/styles/brown-paper.min.css'
    codepen-embed: '/styles/codepen-embed.min.css'
    color-brewer: '/styles/color-brewer.min.css'
    cybertopia-cherry: '/styles/cybertopia-cherry.min.css'
    cybertopia-dimmer: '/styles/cybertopia-dimmer.min.css'
    cybertopia-icecap: '/styles/cybertopia-icecap.min.css'
    cybertopia-saturated: '/styles/cybertopia-saturated.min.css'
    dark: '/styles/dark.min.css'
    default: '/styles/default.min.css'
    devibeans: '/styles/devibeans.min.css'
    docco: '/styles/docco.min.css'
    dracula: '/styles/dracula.min.css'
    far: '/styles/far.min.css'
    felipec: '/styles/felipec.min.css'
    foundation: '/styles/foundation.min.css'
    github-dark-dimmed: '/styles/github-dark-dimmed.min.css'
    github-dark: '/styles/github-dark.min.css'
    github: '/styles/github.min.css'
    gml: '/styles/gml.min.css'
    googlecode: '/styles/googlecode.min.css'
    gradient-dark: '/styles/gradient-dark.min.css'
    gradient-light: '/styles/gradient-light.min.css'
    grayscale: '/styles/grayscale.min.css'
    hybrid: '/styles/hybrid.min.css'
    idea: '/styles/idea.min.css'
    intellij-light: '/styles/intellij-light.min.css'
    ir-black: '/styles/ir-black.min.css'
    isbl-editor-dark: '/styles/isbl-editor-dark.min.css'
    isbl-editor-light: '/styles/isbl-editor-light.min.css'
    kimbie-dark: '/styles/kimbie-dark.min.css'
    kimbie-light: '/styles/kimbie-light.min.css'
    lightfair: '/styles/lightfair.min.css'
    lioshi: '/styles/lioshi.min.css'
    magula: '/styles/magula.min.css'
    mono-blue: '/styles/mono-blue.min.css'
    monokai-sublime: '/styles/monokai-sublime.min.css'
    monokai: '/styles/monokai.min.css'
    night-owl: '/styles/night-owl.min.css'
    nnfx-dark: '/styles/nnfx-dark.min.css'
    nnfx-light: '/styles/nnfx-light.min.css'
    nord: '/styles/nord.min.css'
    obsidian: '/styles/obsidian.min.css'
    panda-syntax-dark: '/styles/panda-syntax-dark.min.css'
    panda-syntax-light: '/styles/panda-syntax-light.min.css'
    paraiso-dark: '/styles/paraiso-dark.min.css'
    paraiso-light: '/styles/paraiso-light.min.css'
    pojoaque: '/styles/pojoaque.min.css'
    purebasic: '/styles/purebasic.min.css'
    qtcreator-dark: '/styles/qtcreator-dark.min.css'
    qtcreator-light: '/styles/qtcreator-light.min.css'
    rainbow: '/styles/rainbow.min.css'
    rose-pine-dawn: '/styles/rose-pine-dawn.min.css'
    rose-pine-moon: '/styles/rose-pine-moon.min.css'
    rose-pine: '/styles/rose-pine.min.css'
    routeros: '/styles/routeros.min.css'
    school-book: '/styles/school-book.min.css'
    shades-of-purple: '/styles/shades-of-purple.min.css'
    srcery: '/styles/srcery.min.css'
    stackoverflow-dark: '/styles/stackoverflow-dark.min.css'
    stackoverflow-light: '/styles/stackoverflow-light.min.css'
    sunburst: '/styles/sunburst.min.css'
    tokyo-night-dark: '/styles/tokyo-night-dark.min.css'
    tokyo-night-light: '/styles/tokyo-night-light.min.css'
    tomorrow-night-blue: '/styles/tomorrow-night-blue.min.css'
    tomorrow-night-bright: '/styles/tomorrow-night-bright.min.css'
    vs: '/styles/vs.min.css'
    vs2015: '/styles/vs2015.min.css'
    xcode: '/styles/xcode.min.css'
    xt256: '/styles/xt256.min.css'
